---
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen %>

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.4
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[ssh_keygen_test::without_passphrase]
      - recipe[ssh_keygen_test::with_passphrase]
      - recipe[ssh_keygen_test::with_user_opts]
